# Permite sobrescrever beans em testes
spring.main.allow-bean-definition-overriding=true

# Configuração do H2 em memória
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Desativa Liquibase em testes
spring.liquibase.enabled=false

# Hibernate cria e destrói o schema automaticamente para cada teste
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Desativa scripts SQL de inicialização
spring.sql.init.mode=never

# Ativa o console web do H2 (opcional, útil para debug)
spring.h2.console.enabled=true


spring.cache.type=simple
