spring.application.name=mekrahm

spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
spring.sql.init.mode=never

#Cache
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=10m
